name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello, world!"

  call-ci:
    uses: ./.github/workflows/reusable-ci.yml
    with:
      node-version: '20'
